### PR TITLE
Add libseat support

### PR DESCRIPTION
**Pull request by charles2910**
For that, we need to enable `libseat` option in `debian/rules`. Since we are building on top of Debian's commits, I tried to make as little changes as possible.

### CODE REVIEW

**Comment by charles2910** [comment]
The [workflow error](https://github.com/torizon/weston-deb/actions/runs/7831755084/job/21368836248?pr=1#step:5:4188) does not happen on a clean chroot nor in gitlab/salsa CI. 

I think the problem is you have feeds enabled for both amd64 and arm in the builder so things go haywire: https://github.com/torizon/weston-deb/actions/runs/7831755084/job/21368836602?pr=1#step:5:665

**Comment by charles2910** [comment]
> I think the problem is you have feeds enabled for both amd64 and arm in the builder so things go haywire: https://github.com/torizon/weston-deb/actions/runs/7831755084/job/21368836602?pr=1#step:5:665

[This line](https://github.com/leonheldattoradex/build-deb-action/blob/ca53f355b32217028bab2914535aff64f7042f88/scripts/install_build_deps#L17) explains a bit of the problem:

```bash

# Adapted from pbuilder's support for cross-compilation:
if [ -n "$INPUT_HOST_ARCH" ]; then
	dpkg --add-architecture "$INPUT_HOST_ARCH"
	INPUT_EXTRA_BUILD_DEPS="$INPUT_EXTRA_BUILD_DEPS crossbuild-essential-$INPUT_HOST_ARCH libc-dev:$INPUT_HOST_ARCH"
	printf 'APT::Get::Host-Architecture "%s";\n' "$INPUT_HOST_ARCH" >> "$APT_CONF_FILE"
fi
```

Setting `INPUT_HOST_ARCH` makes deb-build-action prepares itself for cross-compilation which isn't what we want here. This behaviour is also clarified in the [host-arch's Readme section].

**Comment by leonheldattoradex** [comment]
@charles2910 I don't think I understood why you think having both architectures in the feed messes things up. Isn't the issue related to the wayland-scanner package for armhf? Because if the case was having multiple architecture, why it works for unstable and testing and not for stable?

Failed build: https://github.com/torizon/weston-deb/actions/runs/7831755084/job/21368836602?pr=1
Working build: https://github.com/torizon/weston-deb/actions/runs/7831755084/job/21368837630?pr=1

**Review by leonheldattoradex — APPROVED** [review]
libwayland-bin has some issues and we'll have to rebuild it for cross-compiling so I'm approving even though CI is not working.
@charles2910 please add the details regarding the whys and hows.

**Comment by charles2910** [comment]
Adding the info requested:

There is a bug filled against wayland in Debian BTS ([#939515](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939515)) explaining the issue:

> weston fails to cross build from source, because meson cannot find
> wayland-scanner.pc. It requests wayland-scanner as a native dependency.
> weston declares a build dependency on libwayland-dev. It thus receives
> the host architecture libwayland-dev. libwayland-dev declares a
> depenency on libwayland-bin, which happens to be Multi-Arch: foreign.
> Thus it receives the build architecture libwayland-bin. Unfortunately,
> wayland-scanner.pc, which describes the location of the wayland-scanner
> binary, is shipped in libwayland-dev. So it is only available for the
> host architecture, but required for the build architecture. Please move
> it to libwayland-bin where the wayland-scanner executable lives.

A fix for this was uploaded to Debian unstable but didn't make to bookworm. Our solution is to rebuild bookworm's version with the fix applied.

**Pull request merged**
